### ISSUE TITLE
更新实例报错

### ISSUE THREAD

**Issue by pangzheng** [Dataman-Cloud/swan#668]
![lalo2vwtolznats_315_92 png_620x10000q90g](https://user-images.githubusercontent.com/7556687/27174537-14e51990-51ef-11e7-98d5-2d68d8567bbf.jpg)

发布1应用 100个实例，然后更新提示报错

**Comment by pangzheng** [comment]
centos7-swan:v0.1.11-952cc07

**Comment by pangzheng** [comment]
time="2017-06-16 07:53:55" level=info msg="state scaleUp step, do nothing"
http: panic serving 172.16.1.11:53935: runtime error: invalid memory address or nil pointer dereference
goroutine 24834 [running]:
net/http.(*conn).serve.func1(0xc421c68dc0)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0xa89f80, 0xed4680)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/Dataman-Cloud/swan/src/manager/api.FormTask(0xc421dff8c0, 0xc422b03540)
	/go/src/github.com/Dataman-Cloud/swan/src/manager/api/http_api.go:753 +0x9a
github.com/Dataman-Cloud/swan/src/manager/api.FilterTasksFromApp(0xc4208d0540, 0xc420ac62c0, 0xc420072300, 0xc422ac7800)
	/go/src/github.com/Dataman-Cloud/swan/src/manager/api/http_api.go:656 +0xce
github.com/Dataman-Cloud/swan/src/manager/api.FormAppWithTask(0xc4208d0540, 0xeac9a0)
	/go/src/github.com/Dataman-Cloud/swan/src/manager/api/http_api.go:630 +0x47
github.com/Dataman-Cloud/swan/src/manager/api.(*AppService).ListApp(0xc420017120, 0xc4209e4270, 0xc422360960)
	/go/src/github.com/Dataman-Cloud/swan/src/manager/api/http_api.go:243 +0x1b9
github.com/Dataman-Cloud/swan/src/manager/api.(*AppService).ListApp-fm(0xc4209e4270, 0xc422360960)
	/go/src/github.com/Dataman-Cloud/swan/src/manager/api/http_api.go:48 +0x3e
github.com/Dataman-Cloud/swan/src/manager/api/server/metrics.InstrumentRouteFunc.func1(0xc4209e4270, 0xc422360960)
	/go/src/github.com/Dataman-Cloud/swan/src/manager/api/server/metrics/metrics.go:99 +0x1b7
github.com/Dataman-Cloud/swan/vendor/github.com/emicklei/go-restful.(*Container).dispatch.func6(0xc4209e4270, 0xc422360960)
	/go/src/github.com/Dataman-Cloud/swan/vendor/github.com/emicklei/go-restful/container.go:267 +0x3e
github.com/Dataman-Cloud/swan/vendor/github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc4209e4300, 0xc4209e4270, 0xc422360960)
	/go/src/github.com/Dataman-Cloud/swan/vendor/github.com/emicklei/go-restful/filter.go:21 +0x95
github.com/Dataman-Cloud/swan/src/manager/api/server.(*ApiServer).ProxyRequest.func1(0xc4209e4270, 0xc422360960, 0xc4209e4300)
	/go/src/github.com/Dataman-Cloud/swan/src/manager/api/server/server.go:186 +0xa36
github.com/Dataman-Cloud/swan/vendor/github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc4209e4300, 0xc4209e4270, 0xc422360960)
	/go/src/github.com/Dataman-Cloud/swan/vendor/github.com/emicklei/go-restful/filter.go:19 +0x68
github.com/Dataman-Cloud/swan/src/manager/api/server.(*ApiServer).NCSACommonLogFormatLogger.func1(0xc4209e4270, 0xc422360960, 0xc4209e4300)
	/go/src/github.com/Dataman-Cloud/swan/src/manager/api/server/server.go:169 +0x8b
github.com/Dataman-Cloud/swan/vendor/github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc4209e4300, 0xc4209e4270, 0xc422360960)
	/go/src/github.com/Dataman-Cloud/swan/vendor/github.com/emicklei/go-restful/filter.go:19 +0x68
github.com/Dataman-Cloud/swan/vendor/github.com/emicklei/go-restful.CrossOriginResourceSharing.Filter(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420e40d80, ...)
	/go/src/github.com/Dataman-Cloud/swan/vendor/github.com/emicklei/go-restful/cors_filter.go:40 +0xb5
github.com/Dataman-Cloud/swan/vendor/github.com/emicklei/go-restful.(CrossOriginResourceSharing).Filter-fm(0xc4209e4270, 0xc422360960, 0xc4209e4300)
	/go/src/github.com/Dataman-Cloud/swan/src/manager/api/server/server.go:75 +0x7c
github.com/Dataman-Cloud/swan/vendor/github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc4209e4300, 0xc4209e4270, 0xc422360960)
	/go/src/github.com/Dataman-Cloud/swan/vendor/github.com/emicklei/go-restful/filter.go:19 +0x68
github.com/Dataman-Cloud/swan/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc420977560, 0xea8400, 0xc4202140e0, 0xc420191400)
	/go/src/github.com/Dataman-Cloud/swan/vendor/github.com/emicklei/go-restful/container.go:269 +0x9c6
github.com/Dataman-Cloud/swan/vendor/github.com/emicklei/go-restful.(*Container).(github.com/Dataman-Cloud/swan/vendor/github.com/emicklei/go-restful.dispatch)-fm(0xea8400, 0xc4202140e0, 0xc420191400)
	/go/src/github.com/Dataman-Cloud/swan/vendor/github.com/emicklei/go-restful/container.go:120 +0x48
net/http.HandlerFunc.ServeHTTP(0xc420e19830, 0xea8400, 0xc4202140e0, 0xc420191400)
	/usr/local/go/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0xc420a19d70, 0xea8400, 0xc4202140e0, 0xc420191400)
	/usr/local/go/src/net/http/server.go:2238 +0x130
github.com/Dataman-Cloud/swan/vendor/github.com/emicklei/go-restful.(*Container).ServeHTTP(0xc420977560, 0xea8400, 0xc4202140e0, 0xc420191400)
	/go/src/github.com/Dataman-Cloud/swan/vendor/github.com/emicklei/go-restful/container.go:287 +0x4d
net/http.serverHandler.ServeHTTP(0xc420e92420, 0xea8400, 0xc4202140e0, 0xc420191400)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc421c68dc0, 0xea9100, 0xc422b05680)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
